### ISSUE TITLE
Conjuntos y Relaciones

### ISSUE THREAD

**Issue by Maricruz-Gomz** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Maricruz-Gomz#2]
[Mapa mental- conjuntos y relaciones-23620080.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Maricruz-Gomz/files/12674471/Mapa.mental-.conjuntos.y.relaciones-23620080.pdf)

**Comment by josealfredo79** [comment]
Calificacion

**Comment by LuisAlexisMorales** [comment]
Manejo conceptual:25%
Relación entre concepto:25%
Calidad de la presentación:25%
Jerarquía:25%
Total:100%.  CalFinal:20%
Calificado por el equipo de: Luis Alexis Morales

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
